# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ractions.proto\x12\x08poker.v1\"~\n\x06\x41\x63tion\x12%\n\x04\x66old\x18\x01 \x01(\x0b\x32\x15.poker.v1.Action.FoldH\x00\x12#\n\x03\x62\x65t\x18\x02 \x01(\x0b\x32\x14.poker.v1.Action.BetH\x00\x1a\x06\n\x04\x46old\x1a\x15\n\x03\x42\x65t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x04\x42\t\n\x07payloadb\x06proto3')



_ACTION = DESCRIPTOR.message_types_by_name['Action']
_ACTION_FOLD = _ACTION.nested_types_by_name['Fold']
_ACTION_BET = _ACTION.nested_types_by_name['Bet']
Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {

  'Fold' : _reflection.GeneratedProtocolMessageType('Fold', (_message.Message,), {
    'DESCRIPTOR' : _ACTION_FOLD,
    '__module__' : 'actions_pb2'
    # @@protoc_insertion_point(class_scope:poker.v1.Action.Fold)
    })
  ,

  'Bet' : _reflection.GeneratedProtocolMessageType('Bet', (_message.Message,), {
    'DESCRIPTOR' : _ACTION_BET,
    '__module__' : 'actions_pb2'
    # @@protoc_insertion_point(class_scope:poker.v1.Action.Bet)
    })
  ,
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'actions_pb2'
  # @@protoc_insertion_point(class_scope:poker.v1.Action)
  })
_sym_db.RegisterMessage(Action)
_sym_db.RegisterMessage(Action.Fold)
_sym_db.RegisterMessage(Action.Bet)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTION._serialized_start=27
  _ACTION._serialized_end=153
  _ACTION_FOLD._serialized_start=113
  _ACTION_FOLD._serialized_end=119
  _ACTION_BET._serialized_start=121
  _ACTION_BET._serialized_end=142
# @@protoc_insertion_point(module_scope)
