# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'actions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ractions.proto\x12\x08poker.v1\"\xb0\x01\n\x06\x41\x63tion\x12%\n\x04\x66old\x18\x01 \x01(\x0b\x32\x15.poker.v1.Action.FoldH\x00\x12#\n\x03\x62\x65t\x18\x02 \x01(\x0b\x32\x14.poker.v1.Action.BetH\x00\x12\'\n\x05ready\x18\x03 \x01(\x0b\x32\x16.poker.v1.Action.ReadyH\x00\x1a\x06\n\x04\x46old\x1a\x15\n\x03\x42\x65t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x04\x1a\x07\n\x05ReadyB\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTION']._serialized_start=28
  _globals['_ACTION']._serialized_end=204
  _globals['_ACTION_FOLD']._serialized_start=155
  _globals['_ACTION_FOLD']._serialized_end=161
  _globals['_ACTION_BET']._serialized_start=163
  _globals['_ACTION_BET']._serialized_end=184
  _globals['_ACTION_READY']._serialized_start=186
  _globals['_ACTION_READY']._serialized_end=193
# @@protoc_insertion_point(module_scope)
