# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cards.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61rds.proto\x12\x08poker.v1\"B\n\x04\x43\x61rd\x12\x1c\n\x04rank\x18\x01 \x01(\x0e\x32\x0e.poker.v1.Rank\x12\x1c\n\x04suit\x18\x02 \x01(\x0e\x32\x0e.poker.v1.Suit*\xdf\x01\n\x04Rank\x12\x14\n\x10RANK_UNSPECIFIED\x10\x00\x12\x0c\n\x08RANK_TWO\x10\x01\x12\x0e\n\nRANK_THREE\x10\x02\x12\r\n\tRANK_FOUR\x10\x03\x12\r\n\tRANK_FIVE\x10\x04\x12\x0c\n\x08RANK_SIX\x10\x05\x12\x0e\n\nRANK_SEVEN\x10\x06\x12\x0e\n\nRANK_EIGHT\x10\x07\x12\r\n\tRANK_NINE\x10\x08\x12\x0c\n\x08RANK_TEN\x10\t\x12\r\n\tRANK_JACK\x10\n\x12\x0e\n\nRANK_QUEEN\x10\x0b\x12\r\n\tRANK_KING\x10\x0c\x12\x0c\n\x08RANK_ACE\x10\r*a\n\x04Suit\x12\x14\n\x10SUIT_UNSPECIFIED\x10\x00\x12\x0e\n\nSUIT_CLUBS\x10\x01\x12\x11\n\rSUIT_DIAMONDS\x10\x02\x12\x0f\n\x0bSUIT_HEARTS\x10\x03\x12\x0f\n\x0bSUIT_SPADES\x10\x04\x62\x06proto3')

_RANK = DESCRIPTOR.enum_types_by_name['Rank']
Rank = enum_type_wrapper.EnumTypeWrapper(_RANK)
_SUIT = DESCRIPTOR.enum_types_by_name['Suit']
Suit = enum_type_wrapper.EnumTypeWrapper(_SUIT)
RANK_UNSPECIFIED = 0
RANK_TWO = 1
RANK_THREE = 2
RANK_FOUR = 3
RANK_FIVE = 4
RANK_SIX = 5
RANK_SEVEN = 6
RANK_EIGHT = 7
RANK_NINE = 8
RANK_TEN = 9
RANK_JACK = 10
RANK_QUEEN = 11
RANK_KING = 12
RANK_ACE = 13
SUIT_UNSPECIFIED = 0
SUIT_CLUBS = 1
SUIT_DIAMONDS = 2
SUIT_HEARTS = 3
SUIT_SPADES = 4


_CARD = DESCRIPTOR.message_types_by_name['Card']
Card = _reflection.GeneratedProtocolMessageType('Card', (_message.Message,), {
  'DESCRIPTOR' : _CARD,
  '__module__' : 'cards_pb2'
  # @@protoc_insertion_point(class_scope:poker.v1.Card)
  })
_sym_db.RegisterMessage(Card)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RANK._serialized_start=94
  _RANK._serialized_end=317
  _SUIT._serialized_start=319
  _SUIT._serialized_end=416
  _CARD._serialized_start=25
  _CARD._serialized_end=91
# @@protoc_insertion_point(module_scope)
