# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import errors_pb2 as errors__pb2
import events_pb2 as events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eresponse.proto\x12\x08poker.v1\x1a\x0c\x65rrors.proto\x1a\x0c\x65vents.proto\"^\n\rServerMessage\x12 \n\x05\x65vent\x18\x01 \x01(\x0b\x32\x0f.poker.v1.EventH\x00\x12 \n\x05\x65rror\x18\x02 \x01(\x0b\x32\x0f.poker.v1.ErrorH\x00\x42\t\n\x07payload\"5\n\x08Response\x12)\n\x08messages\x18\x01 \x03(\x0b\x32\x17.poker.v1.ServerMessageb\x06proto3')



_SERVERMESSAGE = DESCRIPTOR.message_types_by_name['ServerMessage']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
ServerMessage = _reflection.GeneratedProtocolMessageType('ServerMessage', (_message.Message,), {
  'DESCRIPTOR' : _SERVERMESSAGE,
  '__module__' : 'response_pb2'
  # @@protoc_insertion_point(class_scope:poker.v1.ServerMessage)
  })
_sym_db.RegisterMessage(ServerMessage)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'response_pb2'
  # @@protoc_insertion_point(class_scope:poker.v1.Response)
  })
_sym_db.RegisterMessage(Response)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVERMESSAGE._serialized_start=56
  _SERVERMESSAGE._serialized_end=150
  _RESPONSE._serialized_start=152
  _RESPONSE._serialized_end=205
# @@protoc_insertion_point(module_scope)
